version: "3.1"

services:
  tgbot:
    container_name: cityinfobot
    build:
      context: .
    command: python bot.py
    # С помощью сети будет соединяться работа бота и контейнер
    networks:
      - botnet
    restart: always
    env_file:
      - ".env"
    volumes:
      - .: /src

networks:
  botnet:
    driver: bridge